M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Tue 26 Sep 2023 10:37:20 PM CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-26T22:37:20+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X54.0Y-54.0
X54.0Y-94.0
X96.0Y-54.0
X96.0Y-94.0
T0
M30
